### ISSUE TITLE
add `Projections` to order by block number & date

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-raw-blocks#14]
https://clickhouse.com/docs/en/sql-reference/statements/alter/projection
```sql
ALTER TABLE transactions ADD PROJECTION transactions_block_projection (
SELECT
*
ORDER BY block_number, block_date
)

ALTER TABLE transactions MATERIALIZE PROJECTION transactions_block_projection
```

**Comment by fschoell** [comment]
No need to add it afterwards, we can include this in the create table statement. See [docs](https://clickhouse.com/docs/en/sql-reference/statements/alter/projection#example-pre-aggregation-query)

**Comment by DenisCarriere** [comment]
Oh nice! can simply add `PROJECTION` 🔥  i'll update that
